CREATE DATABASE Confica;

CREATE TABLE
    `LIVROS` (
        `ID` INT NOT NULL AUTO_INCREMENT,
        `DESCRICAO` VARCHAR(250) NOT NULL DEFAULT '',
        `TITULO` VARCHAR(100) NULL DEFAULT NULL,
        `URL` VARCHAR(250) NULL DEFAULT NULL,
        PRIMARY KEY (`ID`)
    );

SELECT
    *
FROM
    livros